# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('datefrom', models.DateTimeField()),
                ('dateto', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fellowtravellers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fellowtravellers', to='users.User')),
            ],
        ),
    ]
