# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FellowTraveller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='destination',
            name='fellowtravellers',
        ),
        migrations.AddField(
            model_name='fellowtraveller',
            name='fellowdestination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fellowdestination', to='travels.Destination'),
        ),
        migrations.AddField(
            model_name='fellowtraveller',
            name='fellowtraveller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fellowtraveller', to='users.User'),
        ),
    ]
