# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('travels', '0002_auto_20170726_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='users.User'),
            preserve_default=False,
        ),
    ]
